### ISSUE TITLE
java.lang.IllegalArgumentException problem

### ISSUE THREAD

**Issue by lxjuly** [Spasi/LWJGL-FX#6]
Hi Spasi,

This is a wonderful project and I am using it to learn to integrate jwjgl to javaFX. I had set up and run the application but I receive the following error every once in a while. I Googled the error but I didn't seem to find some answer that I can understand. Would you help me advise how to solve this issue? Thank you!
I am using **JDK 8 (update 5) and JavaFX 8, Windows 7 SP1 64bit, OpenGL3.3 with jwjgl 2.9.1**. The compilation level is set to 1.8.

Here is the stacktrace:

```
java.lang.IllegalArgumentException: Upload requires 2563280 elements, but only 2538220 elements remain in the buffer
    at com.sun.prism.impl.BaseTexture.checkUpdateParams(Unknown Source)
    at com.sun.prism.d3d.D3DTexture.update(Unknown Source)
    at com.sun.prism.impl.BaseTexture.update(Unknown Source)
    at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(Unknown Source)
    at com.sun.javafx.sg.prism.NGImageView.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
    at com.sun.javafx.sg.prism.NGImageView.doRender(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
    at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
    at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.renderForClip(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.renderRectClip(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.renderClip(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
    at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
    at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
    at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
    at com.sun.javafx.tk.quantum.ViewPainter.doPaint(Unknown Source)
    at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(Unknown Source)
    at com.sun.javafx.tk.quantum.PresentingPainter.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at com.sun.javafx.tk.RenderJob.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by jiping-s** [comment]
I got that too with nVIDIA (pbuffer-copy render stream). But sometimes it reports like "Upload requires 2563280 elements, but only 2563280 elements remain in the buffer", which seems impossible unless the buffer is being updated from another thread.

**Comment by Spasi** [comment]
Does it happen when you resize the window, or just randomly?

**Comment by jiping-s** [comment]
Randomly. It happens in Java 8u11 on Windows, x64. The problem occurs less if I insert delay between each uploading (copying to image), or if I use the ES2 pipeline.

BTW thanks for you great work!

**Comment by Spasi** [comment]
I've verified that this is a JavaFX bug that only occurs on Java 8 + Nvidia GPUs with the D3D pipeline. I've been trying to figure out a workaround but the only reliable fix is updating the JavaFX view every other frame (effectively cutting the framerate in half).

I will report this to the JavaFX JIRA, as soon as I can.

The change in behavior also negatively affects performance in general, with JavaFX 8 being much slower than JavaFX 2.2. Luckily this one can be fixed, I'll push an update soon.

**Comment by Spasi** [comment]
Actually, it should be fine now, without a framerate hit. Please do let me know how it works if you test this.

**Comment by lxjuly** [comment]
I am away from using JWJGL right now. I will report back if I resume working with it again. Thank you for fixing both issues I reported!
